[package]
name = "bitcoin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
primitive-types = "0.11.1"
num-traits = "0.2.14"
sha2 = "0.10.2"
hmac = '0.12.1'
hex = "0.4.3"
ripemd = "0.1.1"